# DO NOT EDIT MANUALLY
# This is an autogenerated file for unresolved constants.
# Please instead update this file by running `bin/tapioca todo`.

# typed: false

module RSpec::Core::SharedContext; end
module RSpec::Core::Warnings; end
module Truby::DataType; end
