---
name: Ruby

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'
        bundler-cache: true
    - name: Run typechecker
      run: bin/srb tc
    - name: Run tests
      run: bin/rspec --force-color
    - name: Run mutation tests
      run: bin/mutant run
